class AppStrings {
  // 1. Кыргыз тили
  static const Map<String, String> ky = {
    'hello': 'Салам, Асан!',
    'total_balance': 'ЖАЛПЫ БАЛАНС',
    'my_expenses': 'Чыгашалар 📝',
    'sub_label': 'АБОНЕМЕНТ',
    'add_subscription': '+ Абонемент',
    'no_expenses': 'Азырынча эч кандай чыгаша жок.\nПлюс баскычын басып кошуңуз!',
    'deleted': 'өчүрүлдү',
    'calendar_title': 'Чыгашалар календары',
    'no_expenses_day': 'Бул күнү чыгашалар катталган эмес 🌿',
    'select_language': 'Тилди тандоо',
    // Жаңы кошулган саптар:
    'add_expense_title': 'Жаңы чыгаша кошуу',
    'expense_name': 'Чыгашанын аталышы',
    'amount': 'Суммасы (\$)',
    'split_with': 'менен бөлүшүү',
    'save': 'Сактоо',
    'enter_all_fields': 'Сураныч, бардык талааларды толтуруңуз',
    'account_title': 'Аккаунт',
    'preferences': 'Оңдоо-түзөтүү',
    'feedback': 'Сунуштар',
    'logout': 'Чыгуу',
    'app_version': 'Тиркеменин версиясы',
  };

  // 2. Орус тили
  static const Map<String, String> ru = {
    'hello': 'Привет, Асан!',
    'total_balance': 'ОБЩИЙ БАЛАНС',
    'my_expenses': 'Расходы 📝',
    'add_subscription': '+ Абонемент',
    'sub_label': 'АБОНЕМЕНТ',
    'no_expenses': 'Расходов пока нет.\nНажмите плюс, чтобы добавить!',
    'deleted': 'удалено',
    'calendar_title': 'Календарь расходов',
    'no_expenses_day': 'В этот день расходов не было 🌿',
    'select_language': 'Выбор языка',
    // Жаңы кошулган саптар:
    'add_expense_title': 'Добавить новый расход',
    'expense_name': 'Название расхода',
    'amount': 'Сумма (\$)',
    'split_with': 'Поделить с',
    'save': 'Сохранить',
    'enter_all_fields': 'Пожалуйста, заполните все поля',
    'account_title': 'Аккаунт',
    'preferences': 'Настройки',
    'feedback': 'Обратная связь',
    'logout': 'Выйти',
    'app_version': 'Версия приложения',
    'sub_title': 'Управление подписками',
    'select_app': 'Выбор приложения',
    'monthly_price': 'Ежемесячная плата (\$)',
    'payment_day': 'В какой день месяца оплата?',
    'example': 'например:',
    'add_button': 'Добавить абонемент',
    'app_name_hint': 'Название (напр: Netflix)',
  };

  // 3. Англис тили
  static const Map<String, String> en = {
    'hello': 'Hello, Asan!',
    'total_balance': 'TOTAL BALANCE',
    'my_expenses': 'My Expenses 📝',
    'add_subscription': '+ Pass',
    'sub_label': 'PASS',
    'no_expenses': 'No expenses yet.\nTap plus to add one!',
    'deleted': 'deleted',
    'calendar_title': 'Expense Calendar',
    'no_expenses_day': 'No expenses on this day 🌿',
    'select_language': 'Select Language',
    // Жаңы кошулган саптар:
    'add_expense_title': 'Add New Expense',
    'expense_name': 'Expense Name',
    'amount': 'Amount (\$)',
    'split_with': 'Split with',
    'save': 'Save',
    'enter_all_fields': 'Please fill in all fields',
    'account_title': 'Account',
    'preferences': 'Preferences',
    'feedback': 'Feedback',
    'logout': 'Log out',
    'app_version': 'App Version',
    'sub_title': 'Subscription Manager',
    'select_app': 'Select Application',
    'monthly_price': 'Monthly Price (\$)',
    'payment_day': 'Which day of the month is paid?',
    'example': 'example:',
    'add_button': 'Add Pass',
    'app_name_hint': 'App name (e.g. Netflix)',
  };
}
