class AppStrings {
  static const Map<String, Map<String, String>> localizedValues = {
    'ky': {
      'balance_title': 'ЖАЛПЫ БАЛАНС',
      'recent_expenses': 'Акыркы чыгымдар',
      'no_expenses': 'Чыгымдар азырынча жок',
      'upcoming_payments': 'Бүгүнкү иш-чаралар',
      'clear_all': 'Баарын тазалоо',
      'view_all': 'Баарын көрүү',
      'dialog_clear_title': 'Баарын тазалоо',
      'dialog_clear_desc': 'Чын эле бардык чыгымдарды биротоло өчүргүңүз келеби?',
      'yes': 'Ооба',
      'no': 'Жок',
      'cancel': 'Жокко чыгаруу',
      'spotify_title': 'Spotify жазылуусу',
      'spotify_remind': 'Ар бир айдын 12синде',
      'hubs_title': 'Кошелёктор',
      'budget_limit': 'Бюджеттин лимити',
      'create_hub': 'Жаңы кошелёк түзүү',
      'group_direction_label': 'Багыты',
      'type_housing': 'Турак жай',
      'type_cafe': 'Кафе/Майрам',
      'type_travel': 'Саякаттар',
      'type_other': 'Башка',
      'add_new_expense': 'Жаңы чыгым кошуу',
      'settle_up_btn': 'Эсептешүү',
      'after_settle_hint': 'Эсептешкенден кийин бардык чыгымдар нөлгө түшөт',
      'all_debts_closed': 'Бул кошелёк боюнча бардык карыздар жабылган!',
      'settle_dialog_title': 'Эсептешүү',
      'settle_dialog_desc': 'Чын эле бул кошелёк боюнча бардык чыгымдарды нөлгө түшүргүңүз келеби?',
      'settle_success': 'Топтун бардык карыздары ийгиликтүү жабылды!',
      'add_expense_to': 'Буга кошуу:',
      'new_hub_expense': 'Хабдын жаңы чыгымы',
      'expense_title_hint': 'Чыгымдын аталышы',
      'expense_amount_hint': 'Сумма (\$)',
      'validation_error': 'Сураныч, туура маалыматтарды киргизиңиз!',
      'calendar_title': 'Төлөмдөрдүн хроникасы',
      'calendar_subtitle': 'Алдыдагы иш-чаралардын графиги',
      'august': 'Август',
      'events_today_title': 'Бүгүнкү иш-чаралар',
      'internet_title': 'Интернет үчүн төлөм',
      'internet_remind': 'Ар бир айдын 18инде',
      'profile_title': 'Профиль',
      'username_label': 'Колдонуучунун аты',
      'username_hint': 'Сиздин атыңыз',
      'select_language': 'Тилди тандоо',
      'select_currency': 'Валютаны тандоо',
      'delete_account_desc': 'Аккаунтту өчүрүү үчүн Email дарегиңизди ырастаңыз:',
      'email_hint': 'Электрондук почта (Email)',
      'confirm_delete_btn': 'Ырастоо жана өчүрүү',
      'name_saved_success': 'Атыңыз ийгиликтүү сакталды!',
      'name_deleted_success': 'Атыңыз ийгиликтүү өчүрүлдү!',
      'currency_changed_success': 'Валюта ийгиликтүү алмаштырылды!',
      'email_error': 'Ката: Электрондук почта дареги туура эмес киргизилди!',
      'nav_home': 'Башкы',
      'nav_groups': 'Кошелёктор',
      'nav_calendar': 'Календарь',
      'nav_analytics': 'Аналитика',
      'add_new_expense_btn': 'Чыгым кошуу',
      'cat_restaurant': 'РЕСТОРАН',
      'cat_transport': 'Транспорт',
      'cat_entertainment': 'Көңүл ачуу',
      'cat_other': 'Башка',
      'no_hubs_message': 'Кошелёктор азырынча түзүлө элек',
      'no_expenses_message': 'Чыгымдар азырынча жок',
      'no_subscriptions': 'Жазылуулар азырынча жок',
      'subscription_saved': 'Абонемент ийгиликтүү сакталды!',
      'fill_all_fields': 'Сураныч, бардык талааларды толтуруңуз!',
      'invalid_input': 'Баасын же күндү туура эмес киргиздиңиз!',
      // Кыргыз тили сакталган массивдин (ky) ичине:
      'new_subscription_title': 'Жаңы абонемент',
      'add_subscription_header': 'Жазылууну кошуу',
      'hint_title': 'Аталышы (мисалы: YouTube Premium)',
      'hint_amount': 'Баасы (мисалы: 199.00)',
      'hint_day': 'Төлөнүүчү күнү (1-31)',
      'save_button': 'Сактоо',
      'deleted_msg': 'өчүрүлдү',
      'add_expense_title': 'Капчыкка чыгаша кошуу',
'hint_expense_name': 'Чыгашанын аты (мисалы: Тамак-аш)',
'hint_expense_amount': 'Суммасы (RUB)',
'btn_save_expense': 'Чыгашаны сактоо',
'total_wallet_limit': 'КАПЧЫКТЫН ЖАЛПЫ ЛИМИТИ',
'total_spent_lbl': 'Жалпы коротулду:',
'split_with_friends': 'Чыгашаны достор менен бөлүү',
'no_expenses_yet': 'Бул капчыкта азырынча чыгаша жок',
'expense_list_lbl': 'Чыгашалардын тизмеси:',
'create_wallet_title': 'Жаңы капчык түзүү',
'hint_wallet_name': 'Аталышы (мисалы: Той)',
'hint_wallet_limit': 'Лимит / Сумма',
'select_category_lbl': 'Категорияны тандаңыз:',
'btn_add': 'Кошуу',
'no_wallets': 'Капчыктар азырынча жок',
    },
    'ru': {
      'balance_title': 'ОБЩИЙ БАЛАНС',
      'recent_expenses': 'Последние расходы',
      'no_expenses': 'Расходов пока нет',
      'upcoming_payments': 'События на сегодня',
      'clear_all': 'Очистить всё',
      'view_all': 'Смотреть все',
      'dialog_clear_title': 'Очистить всё',
      'dialog_clear_desc': 'Вы действительно хотите безвозвратно удалить все расходы?',
      'yes': 'Да',
      'no': 'Нет',
      'cancel': 'Отмена',
      'spotify_title': 'Подписка Spotify',
      'spotify_remind': 'Каждое 12-е число',
      'hubs_title': 'Кошельки',
      'budget_limit': 'Лимит бюджета',
      'create_hub': 'Создать новый кошелек',
      'group_direction_label': 'Направление',
      'type_housing': 'Жильё',
      'type_cafe': 'Кафе/Праздник',
      'type_travel': 'Поездки',
      'type_other': 'Другое',
      'add_new_expense': 'Добавить новый расход',
      'settle_up_btn': 'Рассчитаться',
      'after_settle_hint': 'После расчета все расходы обнулятся',
      'all_debts_closed': 'Все долги по этому кошельку уже закрыты!',
      'settle_dialog_title': 'Рассчитаться',
      'settle_dialog_desc': 'Вы действительно хотите обнулить все расходы по этому кошельку?',
      'settle_success': 'Все долги группы успешно закрыты!',
      'add_expense_to': 'Добавить в',
      'new_hub_expense': 'Новый расход хаба',
      'expense_title_hint': 'Название расхода',
      'expense_amount_hint': 'Сумма (\$)',
      'validation_error': 'Пожалуйста, введите корректные данные!',
      'calendar_title': 'Хроника платежей',
      'calendar_subtitle': 'График предстоящих событий',
      'august': 'Август',
      'events_today_title': 'События на сегодня',
      'internet_title': 'Оплата за internet',
      'internet_remind': 'Каждое 18-е число',
      'profile_title': 'Профиль',
      'username_label': 'Имя пользователя',
      'username_hint': 'Ваше имя',
      'select_language': 'Выбор языка',
      'select_currency': 'Выбор валюты',
      'delete_account_desc': 'Для удаления аккаунта подтвердите свой Email:',
      'email_hint': 'Электронная почта (Email)',
      'confirm_delete_btn': 'Подтвердить и удалить',
      'name_saved_success': 'Имя успешно сохранено!',
      'name_deleted_success': 'Имя успешно удалено!',
      'currency_changed_success': 'Валюта успешно изменена!',
      'email_error': 'Ошибка: Некорректный адрес электронной почты!',
      'nav_home': 'Главная',
      'nav_groups': 'Кошельки',
      'nav_calendar': 'Календарь',
      'nav_analytics': 'Аналитика',
      'add_new_expense_btn': 'Добавить расход',
      'cat_restaurant': 'РЕСТОРАН',
      'cat_transport': 'Транспорт',
      'cat_entertainment': 'Развлечения',
      'cat_other': 'Другое',
      'no_hubs_message': 'Кошельки пока не созданы',
      'no_expenses_message': 'Расходы пока отсутствуют',
      'no_subscriptions': 'Подписок пока нет',
      'subscription_saved': 'Подписка успешно сохранена!',
      'fill_all_fields': 'Пожалуйста, заполните все поля!',
      'invalid_input': 'Некорректная сумма или день!',
      'new_subscription_title': 'Новый абонемент',
      'add_subscription_header': 'Добавить подписку',
      'hint_title': 'Например, YouTube Premium',
      'hint_amount': 'Сумма (например, 199.00)',
      'hint_day': 'Число списания месяца (1-31)',
      'save_button': 'Сохранить',
      'deleted_msg': 'успешно удалено',
      'add_expense_title': 'Добавить расход в кошелек',
'hint_expense_name': 'Название расхода (например, Продукты)',
'hint_expense_amount': 'Сумма (RUB)',
'btn_save_expense': 'Сохранить расход',
'total_wallet_limit': 'ОБЩИЙ ЛИМИТ КОШЕЛЬКА',
'total_spent_lbl': 'Потрачено всего:',
'split_with_friends': 'Разделить расходы с друзьями',
'no_expenses_yet': 'В этом кошельке расходов пока нет',
'expense_list_lbl': 'Список расходов:',
'no_wallets': 'Кошельков пока нет',
'create_wallet_title': 'Создать новый кошелек',
'hint_wallet_name': 'Название (например, Свадьба)',
'hint_wallet_limit': 'Лимит / Сумма',
'select_category_lbl': 'Выберите категорию:',
'btn_add': 'Добавить',
    },
    'en': {
      'balance_title': 'TOTAL BALANCE',
      'recent_expenses': 'Recent Expenses',
      'no_expenses': 'No expenses yet',
      'upcoming_payments': 'Events for today',
      'clear_all': 'Clear all',
      'view_all': 'View all',
      'dialog_clear_title': 'Clear all',
      'dialog_clear_desc': 'Are you sure you want to permanently delete all expenses?',
      'yes': 'Yes',
      'no': 'No',
      'cancel': 'Cancel',
      'spotify_title': 'Spotify subscription',
      'spotify_remind': 'Every 12th of the month',
      'hubs_title': 'Spaces',
      'budget_limit': 'Budget limit',
      'create_hub': 'Create new space',
      'group_direction_label': 'Direction',
      'type_housing': 'Housing',
      'type_cafe': 'Cafe/Party',
      'type_travel': 'Travel',
      'type_other': 'Other',
      'add_new_expense': 'Add new expense',
      'settle_up_btn': 'Settle Up',
      'after_settle_hint': 'After settling up, all expenses will reset to zero',
      'all_debts_closed': 'All debts for this group are already closed!',
      'settle_dialog_title': 'Settle Up',
      'settle_dialog_desc': 'Are you sure you want to reset all expenses for this group?',
      'settle_success': 'All debts for the group closed successfully!',
      'add_expense_to': 'Add to',
      'new_hub_expense': 'New hub expense',
      'expense_title_hint': 'Expense title',
      'expense_amount_hint': 'Amount (\$)',
      'validation_error': 'Please enter valid information!',
      'calendar_title': 'Payment Timeline',
      'calendar_subtitle': 'Schedule of upcoming events',
      'august': 'August',
      'events_today_title': 'Events for today',
      'internet_title': 'Internet payment',
      'internet_remind': 'Every 18th of the month',
      'profile_title': 'Profile',
      'username_label': 'Username',
      'username_hint': 'Your name',
      'select_language': 'Select Language',
      'select_currency': 'Select Currency',
      'delete_account_desc': 'Confirm your Email address to delete your account:',
      'email_hint': 'Email Address',
      'confirm_delete_btn': 'Confirm and delete',
      'name_saved_success': 'Name saved successfully!',
      'name_deleted_success': 'Name deleted successfully!',
      'currency_changed_success': 'Currency changed successfully!',
      'email_error': 'Error: Incorrect Email address entered!',
      'nav_home': 'Home',
      'nav_groups': 'Spaces',
      'nav_calendar': 'Calendar',
      'nav_analytics': 'Analytics',
      'add_new_expense_btn': 'Add expense',
      'cat_restaurant': 'RESTAURANT',
      'cat_transport': 'Transport',
      'cat_entertainment': 'Entertainment',
      'cat_other': 'Other',
      'no_hubs_message': 'No wallets created yet',
      'no_expenses_message': 'No expenses yet',
      'no_subscriptions': 'No subscriptions yet',
      'subscription_saved': 'Subscription successfully saved!',
      'fill_all_fields': 'Please fill in all fields!',
      'invalid_input': 'Invalid amount or day!',
      'add_expense_title': 'Add Expense to Wallet',
'hint_expense_name': 'Expense name (e.g., Grocery)',
'hint_expense_amount': 'Amount (RUB)',
'btn_save_expense': 'Save Expense',
'total_wallet_limit': 'TOTAL WALLET LIMIT',
'total_spent_lbl': 'Total spent:',
'split_with_friends': 'Split bills with friends',
'no_expenses_yet': 'There are no expenses in this wallet yet',
'expense_list_lbl': 'Expense list:',
'no_wallets': 'No wallets yet',
    },
  };

  static Map<String, String> getTranslation(String currentLang) {
    return localizedValues[currentLang] ?? localizedValues['ky']!;
  }
}
