class AppStrings {
  static const Map<String, Map<String, String>> localizedValues = {
    'ky': {
      'balance_title': 'ЖАЛПЫ БАЛАНС',
      'recent_expenses': 'Акыркы чыгымдар',
      'no_expenses': 'Чыгымдар азырынча жок',
      'upcoming_payments': 'Бүгүнкү иш-чаралар',
      'clear_all': 'Баарын тазалоо',
      'view_all': 'Баарын көрүү',
      'dialog_clear_title': 'Баарын тазалоо',
      'dialog_clear_desc': 'Чын эле бардык чыгымдарды биротоло өчүргүңүз келеби?',
      'yes': 'Ооба',
      'no': 'Жок',
      'cancel': 'Жокко чыгаруу',
      'spotify_title': 'Spotify жазылуусу',
      'spotify_remind': 'Ар бир айдын 12синде',
      'hubs_title': 'Кошелёктор',
      'budget_limit': 'Бюджеттин лимити',
      'create_hub': 'Жаңы кошелёк түзүү',
      'group_direction_label': 'Багыты',
      'type_housing': 'Турак жай',
      'type_cafe': 'Кафе/Майрам',
      'type_travel': 'Саякаттар',
      'type_other': 'Башка',
      'add_new_expense': 'Жаңы чыгым кошуу',
      'settle_up_btn': 'Эсептешүү',
      'after_settle_hint': 'Эсептешкенден кийин бардык чыгымдар нөлгө түшөт',
      'all_debts_closed': 'Бул кошелёк боюнча бардык карыздар жабылган!',
      'settle_dialog_title': 'Эсептешүү',
      'settle_dialog_desc': 'Чын эле бул кошелёк боюнча бардык чыгымдарды нөлгө түшүргүңүз келеби?',
      'settle_success': 'Топтун бардык карыздары ийгиликтүү жабылды!',
      'add_expense_to': 'Буга кошуу:',
      'new_hub_expense': 'Хабдын жаңы чыгымы',
      'expense_title_hint': 'Чыгымдын аталышы',
      'expense_amount_hint': 'Сумма (\$)',
      'validation_error': 'Сураныч, туура маалыматтарды киргизиңиз!',
      'calendar_title': 'Төлөмдөрдүн хроникасы',
      'calendar_subtitle': 'Алдыдагы иш-чаралардын графиги',
      'august': 'Август',
      'events_today_title': 'Бүгүнкү иш-чаралар',
      'internet_title': 'Интернет үчүн төлөм',
      'internet_remind': 'Ар бир айдын 18инде',
      'profile_title': 'Профиль',
      'username_label': 'Колдонуучунун аты',
      'username_hint': 'Сиздин атыңыз',
      'select_language': 'Тилди тандоо',
      'select_currency': 'Валютаны тандоо',
      'delete_account_desc': 'Аккаунтту өчүрүү үчүн Email дарегиңизди ырастаңыз:',
      'email_hint': 'Электрондук почта (Email)',
      'confirm_delete_btn': 'Ырастоо жана өчүрүү',
      'name_saved_success': 'Атыңыз ийгиликтүү сакталды!',
      'name_deleted_success': 'Атыңыз ийгиликтүү өчүрүлдү!',
      'currency_changed_success': 'Валюта ийгиликтүү алмаштырылды!',
      'email_error': 'Ката: Электрондук почта дареги туура эмес киргизилди!',
      'nav_home': 'Башкы',
      'nav_groups': 'Кошелёктор',
      'nav_calendar': 'Календарь',
      'nav_analytics': "Профиль",
      'add_new_expense_btn': 'Чыгым кошуу',
      'cat_restaurant': 'РЕСТОРАН',
      'cat_transport': 'Транспорт',
      'cat_entertainment': 'Көңүл ачуу',
      'cat_other': 'Башка',
      'no_hubs_message': 'Кошелёктор азырынча түзүлө элек',
      'no_expenses_message': 'Чыгымдар азырынча жок',
      'no_subscriptions': 'Жазылуулар азырынча жок',
      'subscription_saved': 'Абонемент ийгиликтүү сакталды!',
      'fill_all_fields': 'Сураныч, бардык талааларды толтуруңуз!',
      'invalid_input': 'Баасын же күндү туура эмес киргиздиңиз!',
      'enter_all_fields': 'Сураныч, бардык талааларды толтуруңуз!',
      'edit_name_title': 'Атын өзгөртүү',
      'save': 'Сактоо',
      'amount_hint': 'Сумма (\$)',
      'add': 'Кошуу',
      'reset_success': 'Сырсөздү калыбына келтирүү шилтемеси почтаңызга жөнөтүлдү!',
      'btn_forgot': 'Сырсөздү унутуп койдуңузбу?',
      'txt_dont_have_account': 'Аккаунтуңуз жокпу? ',
      'nav_profile': 'Профиль',
      'analytics_empty_hint': 'Аналитика үчүн маалымат жок',
      'analytics_title': 'Аналитика',
      'monthly_total_label': 'Жалпы',
      'category_analytics_title': 'Категориялар',
      // Кыргыз тили сакталган массивдин (ky) ичине:
      'new_subscription_title': 'Жаңы абонемент',
      'add_subscription_header': 'Жазылууну кошуу',
      'hint_title': 'Аталышы (мисалы: YouTube Premium)',
      'hint_amount': 'Баасы (мисалы: 199.00)',
      'hint_day': 'Төлөнүүчү күнү (1-31)',
      'save_button': 'Сактоо',
      'deleted_msg': 'өчүрүлдү',
      'add_expense_title': 'Капчыкка чыгаша кошуу',
'hint_expense_name': 'Чыгашанын аты (мисалы: Тамак-аш)',
'hint_expense_amount': 'Суммасы (RUB)',
'btn_save_expense': 'Чыгашаны сактоо',
'total_wallet_limit': 'КАПЧЫКТЫН ЖАЛПЫ ЛИМИТИ',
'total_spent_lbl': 'Жалпы коротулду:',
'split_with_friends': 'Чыгашаны достор менен бөлүү',
'no_expenses_yet': 'Бул капчыкта азырынча чыгаша жок',
'expense_list_lbl': 'Чыгашалардын тизмеси:',
'create_wallet_title': 'Жаңы капчык түзүү',
'hint_wallet_name': 'Аталышы (мисалы: Той)',
'hint_wallet_limit': 'Лимит / Сумма',
'select_category_lbl': 'Категорияны тандаңыз:',
'btn_add': 'Кошуу',
'no_wallets': 'Капчыктар азырынча жок',
"mon": "Дш",
  "tue": "Шш",
  "wed": "Шр",
  "thu": "Бш",
  "fri": "Жм",
  "sat": "Иш",
  "sun": "Жш",
  'every_month_day': 'Ар бир айдын {day}-сы',
  'login_title': 'Тиркемеге кирүү',
'password_hint': 'Пароль',
'login_btn': 'Кирүү',
'no_account': 'Аккаунтуңуз жокпу? ',
'register_now': 'Катталуу',
'title_login': 'Тиркемеге кирүү',
'hint_email': 'Email дарек',
'hint_pass': 'Сырсөз',
'hint_empty_email': 'Email дарегиңизди жазыңыз!',
'hint_empty_pass': 'Пароль кеминде 6 тамгадан турушу керек!',
'btn_login': 'Кирүү',
'success_msg': 'Ийгиликтүү кирдиңиз!',
'error_msg': 'Ката: Почта же пароль туура эмес!',
'title_register': 'Жаңы аккаунт түзүү',
'hint_name': 'Колдонуучунун аты',
'hint_empty_name': 'Атыңызды киргизиңиз!',
'btn_register': 'Катталуу',
'have_account': 'Аккаунтуңуз барбы? ',
'btn_login_link': 'Кирүү',
'title_signup': 'Катталуу',
        'hint_empty': 'Талааларды толтуруңуз!',
        'hint_match': 'Сырсөздөр бири-бирине дал келген жок!',
        'btn_signup': 'Катталуу',
        'link_forgot_pass': 'Сырсөздү унуттуңузбу?',
    'txt_no_account': 'Аккаунтуңуз жокпу? ',
    'link_register': 'Катталуу',
    'error_invalid_credentials': 'Электрондук почта же сырсөз туура эмес. Кайра текшерип көрүңүз.',
    'error_network': 'Интернет байланышы жок. Тармакты текшериңиз.',
    'error_unknown': 'Күтүлбөгөн ката кетти. Кийинчерээк кайра аракет кылып көрүңүз.',
    'delete_error_email': 'Ката: Электрондук почта туура эмес жазылды!',
    'delete_dialog_title': 'Кепилдик жана Ырастоо',
    'delete_dialog_content': 'Биз сиздин купуялуулугуңузду сыйлайбыз. "Өчүрүүнү ырастоо" баскычын басканда, сиздин каттоо эсебиңиз жана бардык жеке маалыматтарыңыз Supabase серверинен ДАРОО жана БИРОТОЛО өчүрүлөт. Бул аракетти артка кайтаруу мүмкүн эмес!',
    'delete_btn_cancel': 'Жокко чыгаруу',
    'delete_btn_confirm': 'Өчүрүүнү ырастоо',
    'delete_success_msg': 'Каттоо эсебиңиз жана бардык маалыматтарыңыз ийгиликтүү өчүрүлдү.',
},
    'ru': {
      'balance_title': 'ОБЩИЙ БАЛАНС',
      'recent_expenses': 'Последние расходы',
      'no_expenses': 'Расходов пока нет',
      'upcoming_payments': 'События на сегодня',
      'clear_all': 'Очистить всё',
      'view_all': 'Смотреть все',
      'dialog_clear_title': 'Очистить всё',
      'dialog_clear_desc': 'Вы действительно хотите безвозвратно удалить все расходы?',
      'yes': 'Да',
      'no': 'Нет',
      'cancel': 'Отмена',
      'spotify_title': 'Подписка Spotify',
      'spotify_remind': 'Каждое 12-е число',
      'hubs_title': 'Кошельки',
      'budget_limit': 'Лимит бюджета',
      'create_hub': 'Создать новый кошелек',
      'group_direction_label': 'Направление',
      'type_housing': 'Жильё',
      'type_cafe': 'Кафе/Праздник',
      'type_travel': 'Поездки',
      'type_other': 'Другое',
      'add_new_expense': 'Добавить новый расход',
      'settle_up_btn': 'Рассчитаться',
      'after_settle_hint': 'После расчета все расходы обнулятся',
      'all_debts_closed': 'Все долги по этому кошельку уже закрыты!',
      'settle_dialog_title': 'Рассчитаться',
      'settle_dialog_desc': 'Вы действительно хотите обнулить все расходы по этому кошельку?',
      'settle_success': 'Все долги группы успешно закрыты!',
      'add_expense_to': 'Добавить в',
      'new_hub_expense': 'Новый расход хаба',
      'expense_title_hint': 'Название расхода',
      'expense_amount_hint': 'Сумма (\$)',
      'validation_error': 'Пожалуйста, введите корректные данные!',
      'calendar_title': 'Хроника платежей',
      'calendar_subtitle': 'График предстоящих событий',
      'august': 'Август',
      'events_today_title': 'События на сегодня',
      'internet_title': 'Оплата за internet',
      'internet_remind': 'Каждое 18-е число',
      'profile_title': 'Профиль',
      'username_label': 'Имя пользователя',
      'username_hint': 'Ваше имя',
      'select_language': 'Выбор языка',
      'select_currency': 'Выбор валюты',
      'delete_account_desc': 'Для удаления аккаунта подтвердите свой Email:',
      'email_hint': 'Электронная почта (Email)',
      'confirm_delete_btn': 'Подтвердить и удалить',
      'name_saved_success': 'Имя успешно сохранено!',
      'name_deleted_success': 'Имя успешно удалено!',
      'currency_changed_success': 'Валюта успешно изменена!',
      'email_error': 'Ошибка: Некорректный адрес электронной почты!',
      'nav_home': 'Главная',
      'nav_groups': 'Кошельки',
      'nav_calendar': 'Календарь',
      'nav_analytics': "Профиль",
      'add_new_expense_btn': 'Добавить расход',
      'cat_restaurant': 'РЕСТОРАН',
      'cat_transport': 'Транспорт',
      'cat_entertainment': 'Развлечения',
      'cat_other': 'Другое',
      'no_hubs_message': 'Кошельки пока не созданы',
      'no_expenses_message': 'Расходы пока отсутствуют',
      'no_subscriptions': 'Подписок пока нет',
      'subscription_saved': 'Подписка успешно сохранена!',
      'fill_all_fields': 'Пожалуйста, заполните все поля!',
      'invalid_input': 'Некорректная сумма или день!',
      'enter_all_fields': 'Пожалуйста, заполните все поля!',
      'edit_name_title': 'Изменить имя',
      'save': 'Сохранить',
      'amount_hint': 'Сумма (\$)',
      'add': 'Добавить',
      'reset_success': 'Ссылка для сброса пароля отправлена на вашу почту!',
      'btn_forgot': 'Забыли пароль?',
      'txt_dont_have_account': 'Нет аккаунта? ',
      'nav_profile': 'Профиль',
      'analytics_empty_hint': 'Нет данных для аналитики',
      'analytics_title': 'Аналитика',
      'monthly_total_label': 'Всего',
      'category_analytics_title': 'Категории',
      'new_subscription_title': 'Новый абонемент',
      'add_subscription_header': 'Добавить подписку',
      'hint_title': 'Например, YouTube Premium',
      'hint_amount': 'Сумма (например, 199.00)',
      'hint_day': 'Число списания месяца (1-31)',
      'save_button': 'Сохранить',
      'deleted_msg': 'успешно удалено',
      'add_expense_title': 'Добавить расход в кошелек',
'hint_expense_name': 'Название расхода (например, Продукты)',
'hint_expense_amount': 'Сумма (RUB)',
'btn_save_expense': 'Сохранить расход',
'total_wallet_limit': 'ОБЩИЙ ЛИМИТ КОШЕЛЬКА',
'total_spent_lbl': 'Потрачено всего:',
'split_with_friends': 'Разделить расходы с друзьями',
'no_expenses_yet': 'В этом кошельке расходов пока нет',
'expense_list_lbl': 'Список расходов:',
'no_wallets': 'Кошельков пока нет',
'create_wallet_title': 'Создать новый кошелек',
'hint_wallet_name': 'Название (например, Свадьба)',
'hint_wallet_limit': 'Лимит / Сумма',
'select_category_lbl': 'Выберите категорию:',
'btn_add': 'Добавить',
  "mon": "Пн",
  "tue": "Вт",
  "wed": "Ср",
  "thu": "Чт",
  "fri": "Пт",
  "sat": "Сб",
  "sun": "Вс",
  'every_month_day': 'Каждое {day}-е число',
  'login_title': 'Вход в приложение',
'password_hint': 'Пароль',
'login_btn': 'Войти',
'no_account': 'Нет аккаунта? ',
'register_now': 'Зарегистрироваться',
'title_login': 'Вход в приложение',
'hint_email': 'Электронная почта',
'hint_pass': 'Пароль',
'hint_empty_email': 'Введите ваш Email!',
'hint_empty_pass': 'Пароль должен быть не менее 6 символов!',
'btn_login': 'Войти',
'success_msg': 'Успешно вошли!',
'error_msg': 'Ошибка: Почта или пароль неверны!',
'title_register': 'Создание аккаунта',
'hint_name': 'Имя пользователя',
'hint_empty_name': 'Введите ваше имя!',
'btn_register': 'Создать аккаунт',
'have_account': 'Уже есть аккаунт? ',
'btn_login_link': 'Войти',
'title_signup': 'Создать аккаунт',
        'hint_empty': 'Заполните все поля!',
        'hint_match': 'Пароли не совпадают!',
        'btn_signup': 'Зарегистрироваться',
        'link_forgot_pass': 'Забыли пароль?',
    'txt_no_account': 'Нет аккаунта? ',
    'link_register': 'Зарегистрироваться',
    'error_invalid_credentials': 'Неверный email или пароль. Пожалуйста, проверьте введённые данные.',
    'error_network': 'Нет соединения с интернетом. Проверьте подключение.',
    'error_unknown': 'Произошла ошибка. Пожалуйста, попробуйте позже.',
    'delete_error_email': 'Ошибка: Электронная почта введена неверно!',
    'delete_dialog_title': 'Гарантия и Подтверждение',
    'delete_dialog_content': 'Мы уважаем вашу конфиденциальность. При нажатии на кнопку "Подтвердить удаление", ваша учетная запись и все личные данные будут НЕМЕДЛЕННО и БЕЗВОЗВРАТНО удалены с сервера Supabase. Это действие нельзя отменить!',
    'delete_btn_cancel': 'Отмена',
    'delete_btn_confirm': 'Подтвердить удаление',
    'delete_success_msg': 'Ваш аккаунт и все данные успешно удалены.',
    'delete_you_entered': 'Вы ввели:',
  'delete_registered_email': 'Зарегистрирован:',
},
    'en': {
      'balance_title': 'TOTAL BALANCE',
      'recent_expenses': 'Recent Expenses',
      'no_expenses': 'No expenses yet',
      'upcoming_payments': 'Events for today',
      'clear_all': 'Clear all',
      'view_all': 'View all',
      'dialog_clear_title': 'Clear all',
      'dialog_clear_desc': 'Are you sure you want to permanently delete all expenses?',
      'yes': 'Yes',
      'no': 'No',
      'cancel': 'Cancel',
      'spotify_title': 'Spotify subscription',
      'spotify_remind': 'Every 12th of the month',
      'hubs_title': 'Spaces',
      'budget_limit': 'Budget limit',
      'create_hub': 'Create new space',
      'group_direction_label': 'Direction',
      'type_housing': 'Housing',
      'type_cafe': 'Cafe/Party',
      'type_travel': 'Travel',
      'type_other': 'Other',
      'add_new_expense': 'Add new expense',
      'settle_up_btn': 'Settle Up',
      'after_settle_hint': 'After settling up, all expenses will reset to zero',
      'all_debts_closed': 'All debts for this group are already closed!',
      'settle_dialog_title': 'Settle Up',
      'settle_dialog_desc': 'Are you sure you want to reset all expenses for this group?',
      'settle_success': 'All debts for the group closed successfully!',
      'add_expense_to': 'Add to',
      'new_hub_expense': 'New hub expense',
      'expense_title_hint': 'Expense title',
      'expense_amount_hint': 'Amount (\$)',
      'validation_error': 'Please enter valid information!',
      'calendar_title': 'Payment Timeline',
      'calendar_subtitle': 'Schedule of upcoming events',
      'august': 'August',
      'events_today_title': 'Events for today',
      'internet_title': 'Internet payment',
      'internet_remind': 'Every 18th of the month',
      'profile_title': 'Profile',
      'username_label': 'Username',
      'username_hint': 'Your name',
      'select_language': 'Select Language',
      'select_currency': 'Select Currency',
      'delete_account_desc': 'Confirm your Email address to delete your account:',
      'email_hint': 'Email Address',
      'confirm_delete_btn': 'Confirm and delete',
      'name_saved_success': 'Name saved successfully!',
      'name_deleted_success': 'Name deleted successfully!',
      'currency_changed_success': 'Currency changed successfully!',
      'email_error': 'Error: Incorrect Email address entered!',
      'nav_home': 'Home',
      'nav_groups': 'Spaces',
      'nav_calendar': 'Calendar',
      'nav_analytics': 'Analytics',
      'add_new_expense_btn': 'Add expense',
      'cat_restaurant': 'RESTAURANT',
      'cat_transport': 'Transport',
      'cat_entertainment': 'Entertainment',
      'cat_other': 'Other',
      'no_hubs_message': 'No wallets created yet',
      'no_expenses_message': 'No expenses yet',
      'no_subscriptions': 'No subscriptions yet',
      'subscription_saved': 'Subscription successfully saved!',
      'fill_all_fields': 'Please fill in all fields!',
      'invalid_input': 'Invalid amount or day!',
      'enter_all_fields': 'Please fill in all fields!',
      'edit_name_title': 'Edit name',
      'save': 'Save',
      'amount_hint': 'Amount (\$)',
      'add': 'Add',
      'reset_success': 'The password reset link has been sent to your email!',
      'btn_forgot': 'Forgot password?',
      'txt_dont_have_account': "Don't have an account? ",
      'nav_profile': 'Profile',
      'analytics_empty_hint': 'No analytics data',
      'analytics_title': 'Analytics',
      'monthly_total_label': 'Total',
      'category_analytics_title': 'Categories',
      'add_expense_title': 'Add Expense to Wallet',
'hint_expense_name': 'Expense name (e.g., Grocery)',
'hint_expense_amount': 'Amount (RUB)',
'btn_save_expense': 'Save Expense',
'total_wallet_limit': 'TOTAL WALLET LIMIT',
'total_spent_lbl': 'Total spent:',
'split_with_friends': 'Split bills with friends',
'no_expenses_yet': 'There are no expenses in this wallet yet',
'expense_list_lbl': 'Expense list:',
'no_wallets': 'No wallets yet',
// 'en' (English) блогунун ичине кошуңуз:
'every_month_day': 'Every {day} of the month',
'login_title': 'Sign in to application',
'password_hint': 'Password',
'login_btn': 'Sign In',
'no_account': "Don't have an account? ",
'register_now': 'Register now',
'title_login': 'Sign In',
'hint_email': 'Email Address',
'hint_pass': 'Password',
'hint_empty_email': 'Please enter your Email!',
'hint_empty_pass': 'Password must be at least 6 characters!',
'btn_login': 'Sign In',
'success_msg': 'Successfully logged in!',
'error_msg': 'Error: Invalid Email or password!',
'title_register': 'Create an Account',
'hint_name': 'Username',
'hint_empty_name': 'Please enter your name!',
'btn_register': 'Sign Up',
'have_account': 'Already have an account? ',
'btn_login_link': 'Sign In',
'title_signup': 'Create Account',
        'hint_empty': 'Please fill all fields!',
        'hint_match': 'Passwords do not match!',
        'btn_signup': 'Sign Up',
        'link_forgot_pass': 'Forgot password?',
    'txt_no_account': "Don't have an account? ",
    'link_register': 'Sign up',
    'error_invalid_credentials': 'Invalid email or password. Please check your credentials.',
    'error_network': 'No internet connection. Please check your network.',
    'error_unknown': 'An unexpected error occurred. Please try again later.',
    'delete_error_email': 'Error: The email address was entered incorrectly!',
    'delete_dialog_title': 'Guarantee & Confirmation',
    'delete_dialog_content': 'We respect your privacy. When you click the "Confirm Delete" button, your account and all personal data will be IMMEDIATELY and PERMANENTLY deleted from the Supabase server. This action cannot be undone!',
    'delete_btn_cancel': 'Cancel',
    'delete_btn_confirm': 'Confirm Delete',
    'delete_success_msg': 'Your account and all data have been successfully deleted.',
    },
  };

  static Map<String, String> getTranslation(String currentLang) {
    return localizedValues[currentLang] ?? localizedValues['ky']!;
  }
}
// lib/config/app_strings.dart

class AppString {
  // ==========================================
  // --- РУССКИЙ ЯЗЫК (ru) ---
  // ==========================================
  static const Map<String, String> ru = {
    'title_login': 'Вход в приложение',
    'hint_email': 'Электронная почта',
    'hint_pass': 'Пароль',
    'hint_empty_email': 'Введите ваш Email!',
    'hint_empty_pass': 'Введите пароль!',
    'btn_login': 'Войти',
    'link_forgot_pass': 'Забыли пароль?',
    'msg_reset_sent': 'Ссылка для сброса пароля отправлена на вашу почту!',
    'txt_no_account': 'Нет аккаунта? ',
    'link_register': 'Регистрация',
    'title_account_settings': 'Настройки аккаунта',
    'hint_confirm_email': 'Введите Email для подтверждения',
    
    // Кирүүдөгү каталар (Орусча):
    'error_invalid_credentials': 'Неверный email или пароль. Пожалуйста, проверьте введённые данные.',
    'error_network': 'Нет соединения с интернетом. Проверьте подключение.',
    'error_unknown': 'Произошла ошибка. Пожалуйста, попробуйте позже.',

    // Аккаунтту өчүрүү (Орусча):
    'delete_error_email': 'Ошибка: Электронная почта введена неверно!',
    'delete_dialog_title': 'Гарантия и Подтверждение',
    'delete_dialog_content': 'Мы уважаем вашу конфиденциальность. При нажатии на кнопку "Подтвердить удаление", ваша учетная запись и все личные данные будут НЕМЕДЛЕННО и БЕЗВОЗВРАТНО удалены с сервера Supabase. Это действие нельзя отменить!',
    'delete_btn_cancel': 'Отмена',
    'delete_btn_confirm': 'Подтвердить удаление',
    'delete_success_msg': 'Ваш аккаунт и все данные успешно удалены.',
      'delete_you_entered': 'Вы ввели:',
  'delete_registered_email': 'Зарегистрирован:',

  };

  // ==========================================
  // --- КЫРГЫЗ ТИЛИ (kg) ---
  // ==========================================
  static const Map<String, String> kg = {
    'title_login': 'Тиркемеге кирүү',
    'hint_email': 'Электрондук почта',
    'hint_pass': 'Сырсөз',
    'hint_empty_email': 'Email дарегиңизди жазыңыз!',
    'hint_empty_pass': 'Сырсөздү жазыңыз!',
    'btn_login': 'Кирүү',
    'link_forgot_pass': 'Сырсөздү унутуп койдуңузбу?',
    'msg_reset_sent': 'Сырсөздү калыбына келтирүү шилтемеси почтаңызга жөнөтүлдү!',
    'txt_no_account': 'Аккаунтуңуз жокпу? ',
    'link_register': 'Катталуу',
    'title_account_settings': 'Аккаунт жөндөөлөрү',
    'hint_confirm_email': 'Тастыктоо үчүн Email дарегиңизди киргизиңиз',

    // Кирүүдөгү каталар (Кыргызча):
    'error_invalid_credentials': 'Электрондук почта же сырсөз туура эмес. Кайра текшерип көрүңүз.',
    'error_network': 'Интернет байланышы жок. Тармакты текшериңиз.',
    'error_unknown': 'Күтүлбөгөн ката кетти. Кийинчерээк кайра аракет кылып көрүңүз.',

    // Аккаунтту өчүрүү (Кыргызча):
    'delete_error_email': 'Ката: Электрондук почта туура эмес жазылды!',
    'delete_dialog_title': 'Кепилдик жана Ырастоо',
    'delete_dialog_content': 'Биз сиздин купуялуулугуңузду сыйлайбыз. "Өчүрүүнү ырастоо" баскычын басканда, сиздин каттоо эсебиңиз жана бардык жеке маалыматтарыңыз Supabase серверинен ДАРОО жана БИРОТОЛО өчүрүлөт. Бул аракетти артка кайтаруу мүмкүн эмес!',
    'delete_btn_cancel': 'Жокко чыгаруу',
    'delete_btn_confirm': 'Өчүрүүнү ырастоо',
    'delete_success_msg': 'Каттоо эсебиңиз жана бардык маалыматтарыңыз ийгиликтүү өчүрүлдү.',
      'delete_you_entered': 'Сиз жаздыңыз:',
  'delete_registered_email': 'Катталган:',

  };

  // ==========================================
  // --- АНГЛИЙСКИЙ ЯЗЫК (en) ---
  // ==========================================
  static const Map<String, String> en = {
    'title_login': 'Sign In',
    'hint_email': 'Email Address',
    'hint_pass': 'Password',
    'hint_empty_email': 'Please enter your Email!',
    'hint_empty_pass': 'Please enter your password!',
    'btn_login': 'Sign In',
    'link_forgot_pass': 'Forgot Password?',
    'msg_reset_sent': 'Password reset link has been sent to your email!',
    'txt_no_account': 'Don\'t have an account? ',
    'link_register': 'Sign Up',
    'title_account_settings': 'Account Settings',
    'hint_confirm_email': 'Enter Email to confirm',

    // Кирүүдөгү каталар (Англисче):
    'error_invalid_credentials': 'Invalid email or password. Please check your credentials.',
    'error_network': 'No internet connection. Please check your network.',
    'error_unknown': 'An unexpected error occurred. Please try again later.',

    // Аккаунтту өчүрүү (Англисче):
    'delete_error_email': 'Error: The email address was entered incorrectly!',
    'delete_dialog_title': 'Guarantee & Confirmation',
    'delete_dialog_content': 'We respect your privacy. When you click the "Confirm Delete" button, your account and all personal data will be IMMEDIATELY and PERMANENTLY deleted from the Supabase server. This action cannot be undone!',
    'delete_btn_cancel': 'Cancel',
    'delete_btn_confirm': 'Confirm Delete',
    'delete_success_msg': 'Your account and all data have been successfully deleted.',
      'delete_you_entered': 'You entered:',
  'delete_registered_email': 'Registered:',

  };

  // Тилди аныктап кайтаруучу функция
  static Map<String, String> getTranslation(String langCode) {
    switch (langCode) {
      case 'kg':
        return kg;
      case 'en':
        return en;
      case 'ru':
      default:
        return ru;
    }
  }
}


