class AppStrings {
  static const Map<String, Map<String, String>> localizedValues = {
    'ky': {
      'balance_title': 'ЖАЛПЫ БАЛАНС',
      'recent_expenses': 'Акыркы чыгашалар',
      'no_expenses': 'Чыгымдар азырынча жок',
      'upcoming_payments': 'Бүгүнкү пландалган төлөмдөр',
      'clear_all': 'Баарын өчүрүү',
      'view_all': 'Баарын көрүү',
      'dialog_clear_title': 'Баарын өчүрүү',
      'dialog_clear_desc': 'Чын эле бардык чыгашаларды биротоло тазалагыңыз келеби?',
      'yes': 'Ооба',
      'no': 'Жок',
      'cancel': 'Жокко чыгаруу',
      'spotify_title': 'Spotify жазылуусу',
      'spotify_remind': 'Ар айдын 12синде',
      'hubs_title': 'Капчыктар',
      'budget_limit': 'Бюджеттин лимити',
      'create_hub': 'Жаңы капчык түзүү',
      'group_direction_label': 'Багыты',
      'type_housing': 'Үй-жай',
      'type_cafe': 'Кафе/Майрам',
      'type_travel': 'Сапарлар',
      'type_other': 'Башка',
      'add_new_expense': 'Жаңы чыгым кошуу',
      'settle_up_btn': 'Эсептешүү',
      'after_settle_hint': 'Эсептешкенден кийин бардык чыгымдар нөлгө түшөт',
      'all_debts_closed': 'Бул капчык боюнча бардык карыздар жабылган!',
      'settle_dialog_title': 'Эсептешүү',
      'settle_dialog_desc': 'Бул капчык боюнча бардык чыгымдарды нөлдөөнү каалайсызбы?',
      'settle_success': 'Бардык карыздар ийгиликтүү жабылды!',
      'add_expense_to': 'Кошуу',
      'new_hub_expense': 'Чыгашаны бөлүшүү',
      'expense_title_hint': 'Чыгымдын аталышы',
      'expense_amount_hint': 'Суммасы (\$)',
      'validation_error': 'Сураныч, маалыматты туура киргизиңиз!',
      'calendar_title': 'Төлөмдөрдүн хроникасы',
      'calendar_subtitle': 'Алдыдагы пландалган иш-чаралардын графиги',
      'august': 'Август',
      'events_today_title': 'Бүгүнкү иш-чаралар',
      'internet_title': 'Интернет үчүн төлөм',
      'internet_remind': 'Ар айдын 18инде',
      'profile_title': 'Профиль',
      'username_label': 'Колдонуучунун ысымы',
      'username_hint': 'Сиздин ысымыңыз',
      'select_language': 'Тилди тандоо',
      'delete_account_desc': 'Аккаунтуңузду өчүрүү үчүн Email дарегиңизди ырастаңыз:',
      'email_hint': 'Электрондук почта (Email)',
      'confirm_delete_btn': 'Ырастоо жана өчүрүү',
      'name_saved_success': 'Ысым ийгиликтүү сакталды!',
      'name_deleted_success': 'Ысым ийгиликтүү өчүрүлдү!',
      'email_error': 'Ката: Электрондук почта туура эмес жазылды!',
      'nav_home': 'Башкы бет',
      'nav_groups': 'Капчыктар',
      'nav_calendar': 'Календарь',
      'nav_analytics': 'Аналитика',
      'add_new_expense_btn': 'Чыгаша кошуу',
      'no_hubs_message': 'Капчыктар азырынча жок',
      'no_expenses_message': 'Чыгашалар азырынча жок',
    },
    'ru': {
      'balance_title': 'ОБЩИЙ БАЛАНС',
      'recent_expenses': 'Последние расходы',
      'no_expenses': 'Расходов пока нет',
      'upcoming_payments': 'События на сегодня',
      'clear_all': 'Очистить всё',
      'view_all': 'Смотреть все',
      'dialog_clear_title': 'Очистить всё',
      'dialog_clear_desc': 'Вы действительно хотите безвозвратно удалить все расходы?',
      'yes': 'Да',
      'no': 'Нет',
      'cancel': 'Отмена',
      'spotify_title': 'Подписка Spotify',
      'spotify_remind': 'Каждое 12-е число',
      'hubs_title': 'Кошельки',
      'budget_limit': 'Лимит бюджета',
      'create_hub': 'Создать новый кошелек',
      'group_direction_label': 'Направление',
      'type_housing': 'Жильё',
      'type_cafe': 'Кафе/Праздник',
      'type_travel': 'Поездки',
      'type_other': 'Другое',
      'add_new_expense': 'Добавить новый расход',
      'settle_up_btn': 'Рассчитаться',
      'after_settle_hint': 'После расчета все расходы обнулятся',
      'all_debts_closed': 'Все долги по этому кошельку уже закрыты!',
      'settle_dialog_title': 'Рассчитаться',
      'settle_dialog_desc': 'Вы действительно хотите обнулить все расходы по этому кошельку?',
      'settle_success': 'Все долги группы успешно закрыты!',
      'add_expense_to': 'Добавить в',
      'new_hub_expense': 'Новый расход хаба',
      'expense_title_hint': 'Название расхода',
      'expense_amount_hint': 'Сумма (\$)',
      'validation_error': 'Пожалуйста, введите корректные данные!',
      'calendar_title': 'Хроника платежей',
      'calendar_subtitle': 'График предстоящих событий',
      'august': 'Август',
      'events_today_title': 'События на сегодня',
      'internet_title': 'Оплата за интернет',
      'internet_remind': 'Каждое 18-е число',
      'profile_title': 'Профиль',
      'username_label': 'Имя пользователя',
      'username_hint': 'Ваше имя',
      'select_language': 'Выбор языка',
      'delete_account_desc': 'Для удаления аккаунта подтвердите свой Email:',
      'email_hint': 'Электронная почта (Email)',
      'confirm_delete_btn': 'Подтвердить и удалить',
      'name_saved_success': 'Имя успешно сохранено!',
      'name_deleted_success': 'Имя успешно удалено!',
      'email_error': 'Ошибка: Некорректный адрес электронной почты!',
      'nav_home': 'Главная',
      'nav_groups': 'Кошельки',
      'nav_calendar': 'Календарь',
      'nav_analytics': 'Аналитика',
      'add_new_expense_btn': 'Добавить расход',
      'cat_restaurant': 'РЕСТОРАН',
'cat_transport': 'Транспорт',
'cat_entertainment': 'Развлечения',
'cat_other': 'Другое',
'no_hubs_message': 'Кошельки пока не созданы',
'no_expenses_message': 'Расходы пока отсутствуют',
    },
    'en': {
      'balance_title': 'TOTAL BALANCE',
      'recent_expenses': 'Recent Expenses',
      'no_expenses': 'No expenses yet',
      'upcoming_payments': 'Events for today',
      'clear_all': 'Clear all',
      'view_all': 'View all',
      'dialog_clear_title': 'Clear all',
      'dialog_clear_desc': 'Are you sure you want to permanently delete all expenses?',
      'yes': 'Yes',
      'no': 'No',
      'cancel': 'Cancel',
      'spotify_title': 'Spotify subscription',
      'spotify_remind': 'Every 12th of the month',
      'hubs_title': 'Spaces',
      'budget_limit': 'Budget limit',
      'create_hub': 'Create new space',
      'group_direction_label': 'Direction',
      'type_housing': 'Housing',
      'type_cafe': 'Cafe/Party',
      'type_travel': 'Travel',
      'type_other': 'Other',
      'add_new_expense': 'Add new expense',
      'settle_up_btn': 'Settle Up',
      'after_settle_hint': 'After settling up, all expenses will reset to zero',
      'all_debts_closed': 'All debts for this group are already closed!',
      'settle_dialog_title': 'Settle Up',
      'settle_dialog_desc': 'Are you sure you want to reset all expenses for this group?',
      'settle_success': 'All debts for the group closed successfully!',
      'add_expense_to': 'Add to',
      'new_hub_expense': 'New hub expense',
      'expense_title_hint': 'Expense title',
      'expense_amount_hint': 'Amount (\$)',
      'validation_error': 'Please enter valid information!',
      'calendar_title': 'Payment Timeline',
      'calendar_subtitle': 'Schedule of upcoming events',
      'august': 'August',
      'events_today_title': 'Events for today',
      'internet_title': 'Internet payment',
      'internet_remind': 'Every 18th of the month',
      'profile_title': 'Profile',
      'username_label': 'Username',
      'username_hint': 'Your name',
      'select_language': 'Select Language',
      'delete_account_desc': 'Confirm your Email address to delete your account:',
      'email_hint': 'Email Address',
      'confirm_delete_btn': 'Confirm and delete',
      'name_saved_success': 'Name saved successfully!',
      'name_deleted_success': 'Name deleted successfully!',
      'email_error': 'Error: Incorrect Email address entered!',
      'nav_home': 'Home',
      'nav_groups': 'Spaces',
      'nav_calendar': 'Calendar',
      'nav_analytics': 'Analytics',
      'add_new_expense_btn': 'Add expense',
      'cat_restaurant': 'RESTAURANT',
'cat_transport': 'Transport',
'cat_entertainment': 'Entertainment',
'cat_other': 'Other',
'no_hubs_message': 'No wallets created yet',
'no_expenses_message': 'No expenses yet',
    },
  };

  static Map<String, String> getTranslation(String currentLang) {
    return localizedValues[currentLang] ?? localizedValues['ky']!;
  }
}
